### PR TITLE
Create checkBootstrapTokenEscrowStatus.sh

### PR DESCRIPTION
**Pull request by scottbreenmsft**
Adding a new script that an detect whether or not a device has escrowed it's bootstrap token to Intune.

### CODE REVIEW

**Comment by theneiljohnson** [comment]
Thanks Scott!

**Comment by asman2maani** [comment]
Hello

So I been trying to deploy intune script using the script under apps
section. I’m using the adobe script as a template by changing program names
and the WEBURL link. I have the blob storage Configured and the link does
work I know that for a fact. What am I doing wrong? I did deploy the adobe
script and it did work but trying to deploy my own apps is not working for
me. Please help me out

Thank Asman

**Comment by theneiljohnson** [comment]
I usually recommend starting with the latest sample script from here, currently we’re on 3.0.6
shell-intune-samples/Apps/LatestSampleScript at master · microsoft/shell-intune-samples (github.com)<https://github.com/microsoft/shell-intune-samples/tree/master/Apps/LatestSampleScript>



From: asman2maani ***@***.***>
Date: Friday, 1 April 2022 at 23:16
To: microsoft/shell-intune-samples ***@***.***>
Cc: Neil Johnson ***@***.***>, State change ***@***.***>
Subject: Re: [microsoft/shell-intune-samples] Create checkBootstrapTokenEscrowStatus.sh (PR #46)
Hello

So I been trying to deploy intune script using the script under apps
section. I’m using the adobe script as a template by changing program names
and the WEBURL link. I have the blob storage Configured and the link does
work I know that for a fact. What am I doing wrong? I did deploy the adobe
script and it did work but trying to deploy my own apps is not working for
me. Please help me out

Thank Asman

**Comment by asman2maani** [comment]
Using the 3.0.6 sample and I’m getting this error. Is there something I’m
doing wrong when creating the blob?

Thanks
Asman

Mon Apr

4 17:05:51 CDT 2022

I

Checking if we need Rosetta 2 or not

Mon Apr

4 17:05:51 CDT 2022

Mon Apr

4 17:05:51 CDT 2022

Mon Apr

4 17:05:51 CDT 2022

Mon Apr

4

17:05:51 CDT 2022

Mon Apr

4

17:05:51 CDT 2022

Mon Apr

4

17:05:51 CDT 2022

No instances of C/usr/sbin/softwareupdate] found, safe to proceed

Intel processor installed. No need to install Rosetta.

Checking if we need to install or update [GoogleChrome]

[GoogleChrome] not installed, need to download and install

Dock is here,

lets carry on

Mon Apr

4 17:05:51 CDT 2022

Mon Apr

4 17:05:51 CDT 2022

-f] processes to end

Mon Apr

4 17:05:51 CDT 2022

No instances of [curl -f] found,

safe to proceed

Mon Apr

4 17:05:51 CDT 2022

Downloading CooglechromeIhttp:://.
blob.core.wandows.net/intunemacapps/CoonieChrome

ff67dcaca2058skt=2022-04-04T18:33:58Z&ske=2022-04-08T82:39:58Zesks=b&skv=2020-08-04&sprahttps&sv=2020-08-edast-besig-niGGkINkyx4xvs

Mon Apr

4 17:05:51 CDT 2022

11 Feilure to download Chttps://.
blob.core.wändows.net/intunemacapps/GoogleChronetz0(2)
<http://blob.core.xn--wndows-bua.net/intunemacapps/GoogleChronetz0(2)>.

F867dcaca2058skt=2022-04-04T18:33:58Z&ske=2822-04-88T02433:68Zasks=baskv=2020-08-04dsprshttps&sv=2020-08-04&sr-besig-Hi66kINkyxaxvSg

**Comment by theneiljohnson** [comment]
Best to open a specific issue. I can't make much sense of the text provided here, sorry.

**Comment by asman2maani** [comment]
Figured out the issue. In my weburl link there was a “&” and powershell
don’t like & in links. I converted the link to a munch smaller and readable
url using tinyurl

Thanks for all the work you guys do.
Asman

**Comment by theneiljohnson** [comment]
These scripts are meant to be run via bash not powershell. How are you using them?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by asman2maani** [comment]
When testing th weburl I used the powershell console. When you enter a curl
command with the weburl  link it give you error message. But yes im using
th script via bash

**Pull request merged**
